version: '3.4'

services:
    octoprint:
        image: octoprint/octoprint
        restart: unless-stopped
        ports:
            - 8080:80
        devices:
            - /dev/ttyAMA0:/dev/ttyAMA0
            - /dev/ttyUSB0:/dev/ttyUSB69
        volumes:
            - octoprint:/octoprint
        networks:
            - secureprinting

    secureprinting:
        image: secureprinting
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - configs:/app/data
            - uploads:/app/uploads
        environment:
            - OCTOPRINT_URL=http://octoprint:80
            - OCTOPRINT_APIKEY=${OCTOPRINT_APIKEY}
            - SECRET_KEY=${SECRET_KEY}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        networks:
            - secureprinting

volumes:
    octoprint: {}
    configs: {}
    uploads: {}

networks:
    secureprinting: {}
