version: '2.4'

services:
    octoprint:
        image: octoprint/octoprint
        restart: unless-stopped
        ports:
            - 8080:80
            devices:
            - /dev/ttyAMA0:/dev/ttyAMA0
            - /dev/ttyUSB0:/dev/ttyUSB69
        volumes:
            - octoprint:/octoprint
    secureprinting:
        build: .
        image: secureprinting:local
        restart: unless-stopped
        ports:
            - 80:8000
        volumes:
            - configs:/app/data
            - uploads:/app/uploads
        environment:
            - OCTOPRINT_URL=http://octoprint:80
            - OCTOPRINT_APIKEY=${OCTOPRINT_APIKEY}
            - SECRET_KEY=${SECRET_KEY}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}

volumes:
    octoprint: {}
    configs: {}
    uploads: {}
