version: '2.4'

services:
    octoprint:
        image: octoprint/octoprint
        restart: unless-stopped
        ports:
            - 8080:80
        devices:
            - /dev/USB0:/dev/USB0
        volumes:
            - octoprint:/octoprint
    secureprinting:
        build: .
        image: secureprinting:local
        restart: unless-stopped
        ports:
            - 80:8000
        volumes:
            - configs:/app/data
            - uploads:/app/uploads
        environment:
            - OCTOPRINT_URL=http://octoprint:80
            - OCTOPRINT_APIKEY=${OCTOPRINT_APIKEY}

volumes:
    octoprint: {}
    configs: {}
    uploads: {}
