# Generated by Django 3.2.7 on 2021-11-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('number', models.TextField(blank=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
