# Generated by Django 3.2.8 on 2021-11-26 23:24

import Website.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='', validators=[Website.models.FileUpload.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['gcode'])]),
        ),
    ]
