# Generated by Django 3.2.7 on 2021-09-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='number',
            field=models.TextField(blank=True),
        ),
    ]
