# Generated by Django 3.2.7 on 2021-10-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0003_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='when_uploaded',
        ),
    ]
