# Generated by Django 2.2.24 on 2021-10-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0004_remove_fileupload_when_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
